---
layout: default
title: Jose Veiga
---
title: Jos√© Veiga
logo: /assets/img/image.jpg
#description: text below image

assets:
  css:
    - /assets/style.css

    
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
